plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# Changelog"
  - - "@semantic-release/npm"
    - npmpublish: false

  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - pnpm-lock.json
      message: |
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}

  - - semantic-release-vsce
    - packageVsix: true
  - - "@semantic-release/github"
    - assets:
        - path: "*.vsix"
          label: Extension File

branches:
  - +([0-9])?(.{+([0-9]),x).x}
  - main
  - { name: develop, prerelease: true }
