name: Test

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.3
        with:
          version: 7
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - if: runner.os == 'Linux'
        run: xvfb-run -a npm test
      - if: runner.os != 'Linux'
        run: npm test

      # - name: Publish
      #   if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest' # success() && : when code part is used
      #   run: npm run deploy
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
